  
version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=kurita
      #- DB_CONNECTION=mongodb://localhost:27017
      - DB_CONNECTION=mongodb://kuritauser:kuritapass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"
  
  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=kuritauser
      - MONGO_INITDB_DATABASE=kurita
      - MONGO_INITDB_ROOT_PASSWORD=kuritapass
volumes:
  dbdata:
